<?if(file_exists($_SERVER["DOCUMENT_ROOT"]."/local/php_interface/include/functions.php")){
    require_once($_SERVER["DOCUMENT_ROOT"]."/local/php_interface/include/functions.php");
}
if(file_exists($_SERVER["DOCUMENT_ROOT"]."/local/php_interface/include/iblock.php")){
    require_once($_SERVER["DOCUMENT_ROOT"]."/local/php_interface/include/iblock.php");
}
if(file_exists($_SERVER["DOCUMENT_ROOT"]."/local/js/include.php")){
    require_once($_SERVER["DOCUMENT_ROOT"]."/local/js/include.php");
}?>
